In [15]:
import pandas as pd
import json

In [23]:
def extract_height(img_data):
    return img_data['size'][0]

def extract_width(img_data):
    return img_data['size'][1]

In [27]:
df = pd.read_json("../data/data.json").T
df['height'] = df['imgdata'].apply(extract_height)
df['width'] = df['imgdata'].apply(extract_width)
df

,category,species_id,breed_id,imgdata,height,width
Abyssinian_100,0,0,0,"{'bbox': [151, 71, 335, 267], 'size': [500, 394]}",500,394
Abyssinian_101,0,0,0,"{'bbox': [54, 36, 319, 235], 'size': [313, 450]}",313,450
Abyssinian_102,0,0,0,"{'bbox': [23, 27, 325, 320], 'size': [465, 500]}",465,500
Abyssinian_103,0,0,0,"{'bbox': [241, 68, 362, 196], 'size': [351, 500]}",351,500
Abyssinian_105,0,0,0,"{'bbox': [237, 101, 373, 227], 'size': [375, 5...",375,500
...,...,...,...,...,...,...
yorkshire_terrier_187,36,1,24,"{'bbox': [187, 49, 317, 181], 'size': [334, 500]}",334,500
yorkshire_terrier_188,36,1,24,"{'bbox': [94, 36, 378, 263], 'size': [334, 500]}",334,500
yorkshire_terrier_189,36,1,24,"{'bbox': [274, 84, 402, 207], 'size': [334, 500]}",334,500
yorkshire_terrier_18,36,1,24,"{'bbox': [52, 23, 289, 183], 'size': [375, 500]}",375,500
yorkshire_terrier_190,36,1,24,"{'bbox': [78, 62, 305, 256], 'size': [500, 406]}",500,406